#ifndef INGOT_SHADER_EMBED_H
#define INGOT_SHADER_EMBED_H

// Shader source strings — generated by embed_shaders.sh at build time.
// Each .metal file becomes a const char* variable.

extern const char *shader_matmul_src;
extern const char *shader_rmsnorm_src;
extern const char *shader_rope_src;
extern const char *shader_softmax_src;
extern const char *shader_elementwise_src;
extern const char *shader_attention_src;
extern const char *shader_moe_gate_src;
extern const char *shader_deltanet_src;

#endif
